---
app_name: "{{ your_app_name }}"
app_dir:  "{{ your_app_dir }}"
context_path: "{{ your_app_context_path }}"
server_host: "{{ hostvars[your_app_server_host].ansible_ssh_host }}"
server_port: "{{ your_app_server_port }}"
nginx_server_group: "{{ your_nginx_server_group }}"
nginx_conf_upstream_dir: "{{ your_nginx_conf_upstream_dir | default('/home/cubedrive/nginx/conf/upstreams.d') }}"
supervisor_conf_dir: "{{ your_supervisor_conf_dir | default('/etc/supervisor/conf.d/') }}"
docker_data_dir: "{{ your_docker_data_dir | default('/home/cubedrive/docker-data') }}"
mysqld_port: "{{ your_mysqld_port }}"
mysql_root_password: "{{ your_mysql_root_password }}"
mongod_port: "{{ your_mongod_port }}"
mongo_root_username: "{{ your_mongo_root_username }}"
mongo_root_password: "{{ your_mongo_root_password }}"

