---

- name: mkdir app dir
  file: path={{ app_dir }} state=directory owner="cubedrive" mode=0775

- name: template your supervisor conf
  template: src=supervisor_app.j2 dest="{{ supervisor_conf_dir }}/{{ app_name }}.conf"
  notify:
  - "update supervisord"

- name: template your nginx conf
  template: src=nginx_upstream.j2 dest="{{ nginx_conf_upstream_dir }}"
  delegate_to: "{{ nginx_host }}"


- name: create a jenkins job
  local_action: jenkins_job config="{{ lookup('template', 'jenkins_project.xml.j2') }}" name={{ app_name }} user="jenkinsAdmin" password="jenkins@Qaz222" url="http://112.74.42.37:4080/jenkins"
  become: False
