- name: debug bla bla
  hosts: all
  remote_user: cubedrive

  tags: ["foo"]
  tasks: 
# Example that prints the loopback address and gateway for each host
  - name: "show some variables"
    debug:
      msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

#   - debug:
#       msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
#     when: ansible_default_ipv4.gateway is defined

  - shell: /usr/bin/uptime
    register: result

  - debug:
      var: result
      verbosity: 2

  - name: Display all variables/facts known for a host
    debug:
      var: hostvars[inventory_hostname]
      verbosity: 4

  - name: Display some variables
    debug:
      msg: 
      - "hostvars: {{ hostvars }}"
      - "group_names: {{ group_names }}"
      - "groups: {{ groups }}"
      - "play_hosts: {{ play_hosts }}"
      - "home dir: {{ ansible_env.HOME }}"
      - "foo: {{ foo | default('foo') | regex_replace('-', '') + '-xyz'}}"
    tags: ["bar"]

