---
- name: Install Docker
  hosts: all
  remote_user: cubedrive
  become: yes
  become_method: sudo

  roles:
    - role: angstwad.docker_ubuntu
      daemon_json: 
        registry-mirrors:
        - 'http://0d358aff.m.daocloud.io'