---
- name: install wkhtmltox
  hosts: all
  remote_user: cubedrive
  become: yes
  become_method: sudo
  gather_facts: no

  vars:
  - font_download_dir: "/home/zzy/Downloads/fonts"
  - wkhtmltox_download_dir: "/home/zzy/Downloads"

  tasks:
  - name: Check if wkhtmltox.tar.xz exists
    local_action: stat path={{wkhtmltox_download_dir}}/wkhtmltox
    ignore_errors: True
    register: wkhtmltox_exists
    become: False



  - name: download wkhtmltox
    local_action: unarchive src="https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz" dest="{{ wkhtmltox_download_dir }}" remote_src=yes
    when: wkhtmltox_exists.stat.exists != True
    become: False

  - name: copy wkhtmltox
    copy: src={{ item }} dest="/usr/bin"
    with_items:
    - "{{ wkhtmltox_download_dir }}/wkhtmltox/bin/wkhtmltopdf"
    - "{{ wkhtmltox_download_dir }}/wkhtmltox/bin/wkhtmltoimage"

  - name: check if simsun.ttc exists
    local_action: stat path={{font_download_dir}}/simsun.ttc
    ignore_errors: True
    register: simsun_exists
    become: False

  - name: download simsun.ttc
    local_action: get_url url="https://github.com/sonatype/maven-guide-zh/raw/master/content-zh/src/main/resources/fonts/simsun.ttc" dest="{{ font_download_dir }}/" mode=0444
    when: simsun_exists.stat.exists != True
    become: False

  - name: copy simsun.ttc
    copy: src={{ font_download_dir }}/simsun.ttc dest="/usr/share/fonts"

